# this is name of the workflow that will be desplayed in the action tab
name: CICD

# manual click deliver workflow whenever user needs
on:
 workflow_dispatch: 

 jobs:
  code:
   runs-on: ubuntu-latest

   steps:
    - name: checkout code
      run: echo "code clonr from Github"
      
  build:
   runs-on: ubuntu-latest  
   steps:
    - name: Build Docker container
      run: echo "Docker Container build"
      
  test:
    runs-on: ubuntu-latest 
    steps:
     - name: Test the container
       run: echo "Testing the container"
      
 deploy:
   runs-on: ubuntu-latest 
   steps:
    - name: Deploying the app
      run: echo "Docker compose deployed the app"
  
  
